### ISSUE TITLE
Discussion: Ideas

### ISSUE THREAD

**Issue by A** [A/textr#11]
- [ ] vim plugin
- [ ] atom plugin
- [ ] sublime plugin
- [x] cli

**Comment by matmuchrapna** [comment]
For editor-based plugins we are blocked by this issue http://talk.commonmark.org/t/is-there-any-way-to-transform-ast-tree-back-to-markdown/1143

**Comment by iamstarkov** [comment]
language packs like cssnext pack for postcss

**Comment by iamstarkov** [comment]
btw, what did you mean by editor plugins?

**Comment by denysdovhan** [comment]
cli could be checked, I think

**Comment by shuvalov-anton** [comment]
done :P

**Comment by gooosev** [comment]
wtf
