### ISSUE TITLE
textr’s purpose and mission is not clear

### ISSUE THREAD

**Issue by iamstarkov** [A/textr#14]
Consumers expect Textr to be a typographic engine itself rather than a tool for creating custom ones. And this confusion is entirely our fault.

**Comment by vladimirstarkov** [comment]
maybe we should get rid of the textarea playground to not confuse people about textr’s purpose

**Comment by shuvalov-anton** [comment]
-1 from me. Playground is great place to show textr abilities. It's work better then stories from readme. But can we clear playground description to help users understand the idea?

**Comment by vladimirstarkov** [comment]
2cent contra: people usually prefer interactive over static, so playground will shade on text and nobody will read the description.

**Comment by vladimirstarkov** [comment]
we can always have separate page for demo

**Comment by vladimirstarkov** [comment]
> -1 from me. Playground is great place to show textr abilities.

Textr make ii is possible not to "typograph" you text, but to create your own text transform engine, that’s why demo playground is not perfect for showing textr possiblities

**Comment by vladimirstarkov** [comment]
. @pepelsbey have been confused about purpose too

**Comment by vladimirstarkov** [comment]
Maybe list of plugins with transformation samples from them can help to show potential textr abilities?

**Comment by pepelsbey** [comment]
Who needs a platform without basic plugins that could be used right now? Make a good product that could be used as a typographer by regular users and then you’ll get attention from developers that would extend it for their needs.

**Comment by shuvalov-anton** [comment]
true

**Comment by iamstarkov** [comment]
Everybody need platform and, sure, plugins for it. It’s how gulp, postcss ecosystem is working.

That’s why I agree that we need more basic plugins and at the same time I cannot agree that we need to create real product for regular user to promote textr, because from my point of view it is impossible to do it in proper way for every "usual" user. 

That’s why my suggestion is to take some raw articles, typograph them, convert these materials to tests and then write missing plugins. What do you think?

**Comment by iamstarkov** [comment]
The whole point is that textr is platform to create your own ideal typographic engine, not engine itself. That’s why I’m again vote to reduce textarea’s demo on the site

**Comment by shuvalov-anton** [comment]
> That’s why my suggestion is to take some raw articles, typograph them, convert these materials to tests and then write missing plugins.

> The whole point is that textr is platform to create your own ideal typographic engine, not engine itself. That’s why I’m again vote to reduce textarea’s demo on the site

Ok. I think, that we can create some tool/bundle to typographing text (probably, for russian at the begining) and move the textr's playground to the tool repository.
