### ISSUE TITLE
In-browser use

### ISSUE THREAD

**Issue by tompazourek** [A/textr#22]
Hi,

I was just wondering what are your opinions or ideas on running textr in-browser through something like **require.js**.

Are there any caveats? Could it work?

I guess it depends a lot on which plugins are loaded. But I am wondering about your opinion on this in general.

Cheers

**Comment by denysdovhan** [comment]
textr doesn't have its own deps.
You are able to use it through browserify or webpack, as you wish. Just install textr and plugins using npm and require them in your scripts.

**Comment by iamstarkov** [comment]
@denysdovhan is right

**Comment by tompazourek** [comment]
Thanks a lot, I'll have to try it.

**Comment by iamstarkov** [comment]
@tompazourek  feel free to reopen, if you will face any issue regarding textr
